### ISSUE TITLE
Use Path2D for spawning mobs

### ISSUE THREAD

**Issue by cbscribe** [kidscancode/godot_guides#5]
Suggestion from Lars:

I would recommend using a Path2D node to determine the spawning position of the mobs. Just paint a Path around the visible area, attach a PathFollow2D node and set a random offset.

* Downside:
Changing the size of the viewport won't change the spawn locations, but I'd argue that usually that's what you want. In any case since in this tutorial the screen size is fixed it doesn't affect the result.

* Upsides:
It saves you the code that picks a random edge and a random location on that edge
It saves you the code that determines the (unrandomized) start direction, since PathFollow2D-Nodes rotate along the path by default. You just need to add PI/2 to the rotation, otherwise the PathFollow2D will orient along the path instead of looking into the screen.
It even saves you the rand_range, because offsets on a path wrap around.
So this block of code

```
    #pick a random screen edge
        var edge = randi() % 4
    # based on edge, pick a random spot on that edge
    # and set the direction to point into the screen
        if edge == 0:  # top
                position = Vector2(rand_range(0, screensize.x), 0)
                direction = PI/2
        elif edge == 1:  # right
                position = Vector2(screensize.x, rand_range(0, screensize.y))
                direction = PI
        elif edge == 2:  # bottom
                position = Vector2(rand_range(0, screensize.x), screensize.y)
                direction = PI * 3/2
        elif edge == 3:  # left
                position = Vector2(0, rand_range(0, screensize.y))
                direction = 0
```
would turn into this line of code:
`$"Path2D/PathFollow2D".set_offset(randi())`

**Comment by cbscribe** [comment]
I am torn on this one. It don't think it necessarily removes complexity, as it does add quite a few steps in the GUI:
* Add a Path2D node
* Draw the path (and explain the UI for that)
* Add a PathFollow2D (yet another node type to explain)

**Comment by Warlaan** [comment]
I understand that debate is needed about this one, especially because this solution has a different effect once the screen size changes.

I just want to mention that I didn't have a single programmer that had trouble using the UI, but I rarely had a non-programmer who wouldn't much rather learn the most difficult UI workflows than a slightly complex script.
I am certain that at least 30% of the kind of student that I teach would copy paste that block of code and not take their time to really understand it.

It's true that you would have to explain three more steps / nodes, but I'd argue that that's a benefit rather than a drawback. After all people read this tutorial because they want to learn about Godot, not about modulo maths and radians.
I get your point about keeping the scope of the tutorial down, but my impression is that our view as programmers is distorted on this one, and that a large group would find adding nodes easier than that code, another large group would be interested to learn about Paths and PathFollow nodes and only a minority of the users would prefer to see the code than a UI solution.

**Comment by Warlaan** [comment]
Suggestion: how about letting the reader choose which path they want to take? If the page format does not allow for collapsable boxes simple headers like "step 4a" and "step 4b" and a short note how they are different and that you can skip either of the two chapters should work.

I understand that this would mean more work and more text to proof-read and maintain, but in this case the two solutions are so different and have so different results that it would be justified. 
After all this is supposed to be a starting point, and the code solution allows you to easily modify the size of the playing field and not worry about mobs spawning on screen or too far outside, while the Path solution makes it much easier to create on-screen spawners or change where mobs could come from.

**Comment by cbscribe** [comment]
> Suggestion: how about letting the reader choose which path they want to take?

That could be interesting.  There are no collapsable elements available at the moment, but I know there is currently some work going on updating the javascript/ui.

**Comment by cbscribe** [comment]
After playing around with it for a bit, I've updated the project to use the Path2D solution. Updated doc will follow.

One thing I noted - you have to be sure to draw the points of the path in clockwise order, or the facing direction will be opposite. Will have to make sure the doc is clear on this.

**Comment by cbscribe** [comment]
Added and documented.
