### ISSUE TITLE
RigidBody2D for mobs

### ISSUE THREAD

**Issue by cbscribe** [kidscancode/godot_guides#6]
Suggestion per Lars:

I would use a RigidBody with friction and gravity scale set to 0 and with an empty collision mask for the mobs. After all you want to create a mob that doesn't react to collisions but can be detected and that constantly moves in one direction. That's what a rigidbody with an empty mask does out of the box.

**Comment by cbscribe** [comment]
The problem I have with this is that RigidBody *doesn't* do this out of the box.  Out of the box, the RigidBody falls off the screen.  We have to add several property changes:

* Set friction scale
* Set gravity scale
* Set collision mask

But my main reservation is that I already see too many beginners trying to use RigidBody2D for applications where it's making their task more difficult.  RigidBody requires understanding of applied forces and understanding of the physics engine. It results in a lot of "my object isn't doing what I want it to do" and fighting against the physics.

**Comment by Warlaan** [comment]
What I meant was that a RigidBody2D has that functionality out of the box. And a RigidBody2D with friction and gravity scale set to 0 and the collision mask cleared will do that "out of the box" (as in without additional script code).

I haven't had that experience about beginners misusing RidigBodies, but then I explain the different purposes of the four physics bodies (counting Area) very early on, because I am anticipating that this might happen otherwise.

The thing is that using Areas the way they are used here is technically not correct, and while it doesn't show in this simple game it's not unusual to end up with bugs or at least unexpected behavior because of it.
You are changing the position of a physics object in _process(), but collision information isn't updated until the next time the physics thread updates. I did a quick test and it took two to three frames until the area_entered-signal was sent and get_overlapping_areas() and overlaps_area() returned the expected values. 
Also we had a bug in the past (I don't know whether it's solved yet), where moving one Area on top of another one occasionally triggers the signal only on the instance that didn't move, which suggests that Areas were written with static areas in mind. So even if that bug was fixed I wouldn't be surprised if there were more bugs like this where the Area code might have been tested for non-moving areas only.

So in the end there are three options:
1. Use areas and don't mention these issues.
2. Use areas and explain what that means for timing and precision.
3. Use a RigidBody that doesn't have these issues because it is built for objects that are move in a linear or accelerated way and trigger collision detection.

I think we agree that solution 2 would exceed the scale of this tutorial, and imho option 1 is not a good idea. Out of four projects in our first semester two had physics issues because they tried to use script code instead of using the most suitable physics node with its properties. And out of the remaining two one still needed to learn how _integrate_forces() works in order to achieve what they wanted. So in my experience this is not something that wouldn't happen to the vast majority of users and could therefore be ignored.

It's true that three properties would have to be changed on a RigidBody, but each of these properties changes something visibly on screen. If you start the game first, you'll see that the objects drop "down", once you change gravity scale they don't. Then the objects will slow down, once you change friction they won't. Then the objects will bounce off of each other and when you clear the collision mask they won't.
So imho each of these properties is very easy to understand and both the issue and the effect of the change are clearly visible.

**Comment by cbscribe** [comment]
Your verbosity is convincing me. ;)

> I haven't had that experience about beginners misusing RidigBodies,

That's probably because you're teaching them.  I'm more referencing the issues I've seen in QA and on discord where people didn't necessarily have the best instruction.

> I explain the different purposes of the four physics bodies (counting Area) very early on, because I am anticipating that this might happen otherwise.

I've also volunteered to write that document for just this purpose. I'll be asking you for input on that as well.

Overall given #11 , I'm finding this more palatable.  As you say, it's a more appropriate application of the correct node type.

**Comment by Warlaan** [comment]
Yea, sorry for my tendency to strike with walls of text. ;-) I just have been burned too many times on sites like facebook where I left out a couple of details because I thought they were self-explanatory only to find that an hour later the discussion hat revolved completely around those parts because someone thought he had found a hole in my argumentation.

I don't remember that many cases in the QA section, but it doesn't really matter. If that's your impression then I trust your judgement. Also now that you mention it I remember talking about PhysicsBody vs KinematicBody vs StaticBody vs Area2D quite regularly, so I may just have forgotten about it.

**Comment by cbscribe** [comment]
Change applied
